import { useState, useCallback } from 'react';
import jsPDF from 'jspdf';

/**
 * Convert blob to base64 data URL
 * @param {Blob} blob - Image blob
 * @returns {Promise<string>} - Base64 data URL
 */
const blobToBase64 = (blob) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

/**
 * Sleep utility for chunking
 */
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * usePdfExport Hook
 * Handles PDF export with async processing to avoid blocking the main thread
 * 
 * @param {Object} options - Hook options
 * @param {Object} options.bookData - Book data to export
 * @returns {Object} PDF export state and handlers
 */
export function usePdfExport({ bookData } = {}) {
  const [exporting, setExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);
  const [exportError, setExportError] = useState(null);

  /**
   * Add footer with page number to PDF
   */
  const addFooter = useCallback((doc, pageNum, totalPages, pageWidth, pageHeight, margin) => {
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Living Textbook',
      margin,
      pageHeight - 10
    );
    doc.text(
      new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }),
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  }, []);

  /**
   * Export PDF with async processing
   * Uses requestAnimationFrame and chunking to avoid blocking the main thread
   */
  const exportPDF = useCallback(async () => {
    if (!bookData || !bookData.subject) return;

    setExporting(true);
    setExportProgress(0);
    setExportError(null);

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;

      // === COVER PAGE ===
      // Add gradient background effect with rectangles
      doc.setFillColor(102, 126, 234);
      doc.rect(0, 0, pageWidth, 60, 'F');

      // Title
      doc.setFontSize(28);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255);
      doc.text(bookData.subject, pageWidth / 2, 35, { align: 'center' });

      // Subtitle
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(255);
      doc.text(
        `A ${bookData.settings?.level || 'General'} Level Educational Book`,
        pageWidth / 2,
        45,
        { align: 'center' }
      );

      // Cover image if available - process asynchronously
      if (bookData.image?.blob) {
        try {
          // Yield to main thread
          await sleep(0);
          const imageData = await blobToBase64(bookData.image.blob);
          if (imageData) {
            const coverImageSize = 80;
            const coverImageX = (pageWidth - coverImageSize) / 2;
            doc.addImage(
              imageData,
              'JPEG',
              coverImageX,
              60,
              coverImageSize,
              coverImageSize,
              undefined,
              'FAST'
            );
          }
        } catch (err) {
          console.warn('Cover image failed:', err);
        }
      }

      // Metadata on cover
      doc.setFontSize(10);
      doc.setTextColor(100);
      const metaY = bookData.image?.blob ? 150 : 100;

      if (bookData.settings) {
        doc.text(`Reading Level: ${bookData.settings.level}`, pageWidth / 2, metaY, { align: 'center' });
        doc.text(`Tone: ${bookData.settings.tone > 0.7 ? 'Fun & Playful' : bookData.settings.tone < 0.3 ? 'Academic' : 'Balanced'}`, pageWidth / 2, metaY + 10, { align: 'center' });
        doc.text(`Style: ${bookData.settings.style > 0.7 ? 'Realistic' : bookData.settings.style < 0.3 ? 'Cartoonish' : 'Digital Art'}`, pageWidth / 2, metaY + 20, { align: 'center' });
      }

      doc.text(
        `Created with Living Textbook AI`,
        pageWidth / 2,
        pageHeight - 30,
        { align: 'center' }
      );
      doc.setFontSize(8);
      doc.text(
        `Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        pageWidth / 2,
        pageHeight - 22,
        { align: 'center' }
      );

      // Add page number to cover
      addFooter(doc, 1, (bookData.pages?.length || 1) + 1, pageWidth, pageHeight, margin);

      // === CONTENT PAGES ===
      const pages = bookData.pages || [];
      const totalPages = pages.length + 1; // +1 for cover

      for (let i = 0; i < pages.length; i++) {
        const page = pages[i];
        if (!page) continue;

        // Yield to main thread between pages to prevent freezing
        if (i > 0 && i % 2 === 0) {
          await sleep(0);
        }

        // Update progress
        setExportProgress(Math.round(((i + 1) / pages.length) * 100));

        // Add new page
        doc.addPage();
        const pdfPageNum = i + 2; // +1 for cover, +1 for 0-index

        // Page header with title
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30);
        doc.text(page.title || `Page ${i + 1}`, margin, margin + 10);

        // Page number indicator
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(128);
        doc.text(`Page ${i + 1} of ${pages.length}`, pageWidth - margin, margin + 10, { align: 'right' });

        // Add image if available - process asynchronously
        if (page.image?.blob) {
          try {
            // Yield to main thread before image processing
            await sleep(0);
            const imageData = await blobToBase64(page.image.blob);
            if (imageData) {
              const imageHeight = contentWidth;
              const imageY = margin + 25;

              doc.addImage(
                imageData,
                'JPEG',
                margin,
                imageY,
                contentWidth,
                imageHeight,
                undefined,
                'FAST'
              );

              // Add content text below image
              doc.setFontSize(12);
              doc.setFont('helvetica', 'normal');
              doc.setTextColor(50);
              const textY = imageY + imageHeight + 15;
              const splitText = doc.splitTextToSize(page.content || '', contentWidth);
              doc.text(splitText, margin, textY);
            } else {
              // Fallback: text only
              doc.setFontSize(12);
              doc.setFont('helvetica', 'normal');
              doc.setTextColor(50);
              const splitText = doc.splitTextToSize(page.content || '', contentWidth);
              doc.text(splitText, margin, margin + 25);
            }
          } catch (err) {
            console.warn(`Page ${i + 1} image failed:`, err);
            // Fallback to text only
            doc.setFontSize(12);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(50);
            const splitText = doc.splitTextToSize(page.content || '', contentWidth);
            doc.text(splitText, margin, margin + 25);
          }
        } else {
          // No image - text only
          doc.setFontSize(12);
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(50);
          const splitText = doc.splitTextToSize(page.content || '', contentWidth);
          doc.text(splitText, margin, margin + 25);
        }

        // Add footer
        addFooter(doc, pdfPageNum, totalPages, pageWidth, pageHeight, margin);
      }

      // Set PDF metadata
      doc.setProperties({
        title: bookData.subject,
        subject: `Educational Book - ${bookData.settings?.level || 'General'} Level`,
        author: 'Living Textbook AI',
        creator: 'Living Textbook',
        keywords: `education, ${bookData.subject}, AI-generated, ${bookData.settings?.level || 'general'}`,
        creationDate: new Date(),
      });

      // Yield before saving
      await sleep(0);

      // Save the PDF with formatted filename
      const safeSubject = bookData.subject.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
      const dateStr = new Date().toISOString().split('T')[0];
      const filename = `LivingTextbook_${safeSubject}_${dateStr}.pdf`;
      doc.save(filename);

      setExportProgress(100);
    } catch (error) {
      console.error('PDF export failed:', error);
      setExportError(error.message || 'Failed to export PDF');
    } finally {
      setExporting(false);
    }
  }, [bookData, addFooter]);

  /**
   * Cancel export (reset state)
   */
  const cancelExport = useCallback(() => {
    setExporting(false);
    setExportProgress(0);
    setExportError(null);
  }, []);

  /**
   * Reset export state
   */
  const resetExport = useCallback(() => {
    setExporting(false);
    setExportProgress(0);
    setExportError(null);
  }, []);

  return {
    // State
    exporting,
    exportProgress,
    exportError,

    // Actions
    exportPDF,
    cancelExport,
    resetExport,
  };
}

export default usePdfExport;
