import { useState, useCallback } from 'react';
import jsPDF from 'jspdf';
import type { Book, ImageResult } from '../types';
import type { UsePdfExportReturn } from '../types';

/**
 * Convert blob to base64 data URL
 * @param blob - Image blob
 * @returns Base64 data URL
 */
const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (reader.result) {
        resolve(reader.result as string);
      } else {
        reject(new Error('FileReader returned null'));
      }
    };
    reader.onerror = () => reject(new Error('FileReader error'));
    reader.readAsDataURL(blob);
  });
};

/**
 * Sleep utility for chunking
 */
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Calculate optimal font size to fit text within available page space
 * @param doc - jsPDF instance
 * @param text - Text content
 * @param contentWidth - Available width for text
 * @param availableHeight - Available height for text
 * @param baseFontSize - Starting font size to try
 * @returns Object with fontSize and splitText
 */
const calculateFitText = (
  doc: jsPDF,
  text: string,
  contentWidth: number,
  availableHeight: number,
  baseFontSize: number = 12
): { fontSize: number; splitText: string[] } => {
  const lineHeight = 1.15;
  let fontSize = baseFontSize;
  let splitText: string[] = [];

  // Try decreasing font sizes until text fits
  const fontSizes = [baseFontSize, 11, 10, 9, 8, 7];
  
  for (const size of fontSizes) {
    doc.setFontSize(size);
    splitText = doc.splitTextToSize(text, contentWidth);
    const requiredHeight = splitText.length * size * lineHeight;
    
    if (requiredHeight <= availableHeight) {
      return { fontSize: size, splitText };
    }
  }

  // If even the smallest font doesn't fit, truncate with ellipsis
  doc.setFontSize(7);
  splitText = doc.splitTextToSize(text, contentWidth);
  const maxLines = Math.floor(availableHeight / (7 * lineHeight));
  
  if (splitText.length > maxLines && maxLines > 0) {
    splitText = splitText.slice(0, maxLines);
    // Add ellipsis to last line
    const lastLine = splitText[splitText.length - 1];
    splitText[splitText.length - 1] = lastLine.slice(0, -3) + '...';
  }

  return { fontSize: 7, splitText };
};

/**
 * usePdfExport Hook
 * Handles PDF export with async processing to avoid blocking the main thread
 * Memory-safe: explicitly nullifies base64 strings after use to encourage GC
 *
 * @param options - Hook options
 * @param options.bookData - Book data to export
 * @returns PDF export state and handlers
 */
export function usePdfExport({ bookData }: { bookData?: Book | null } = {}): UsePdfExportReturn {
  const [exporting, setExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);
  const [exportError, setExportError] = useState<string | null>(null);

  /**
   * Add footer with page number to PDF
   */
  const addFooter = useCallback((
    doc: jsPDF,
    pageNum: number,
    totalPages: number,
    pageWidth: number,
    pageHeight: number,
    margin: number
  ) => {
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Living Textbook',
      margin,
      pageHeight - 10
    );
    doc.text(
      new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }),
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  }, []);

  /**
   * Export PDF with async processing
   * Uses requestAnimationFrame and chunking to avoid blocking the main thread
   * Memory-safe: nullifies base64 strings after use
   */
  const exportPDF = useCallback(async () => {
    if (!bookData || !bookData.subject) return;

    setExporting(true);
    setExportProgress(0);
    setExportError(null);

    // Track base64 strings for cleanup
    let base64String: string | null = null;

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;

      // === COVER PAGE ===
      // Add gradient background effect with rectangles
      doc.setFillColor(102, 126, 234);
      doc.rect(0, 0, pageWidth, 60, 'F');

      // Title
      doc.setFontSize(28);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255);
      doc.text(bookData.subject, pageWidth / 2, 35, { align: 'center' });

      // Subtitle
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(255);
      doc.text(
        `A ${bookData.settings?.level || 'General'} Level Educational Book`,
        pageWidth / 2,
        45,
        { align: 'center' }
      );

      // Cover image if available - process asynchronously
      // Note: Book has pages array, cover image would be from first page
      const coverPage = bookData.pages?.[0];
      if (coverPage?.image?.blob) {
        try {
          // Yield to main thread
          await sleep(0);
          base64String = await blobToBase64(coverPage.image.blob);
          if (base64String) {
            const coverImageSize = 80;
            const coverImageX = (pageWidth - coverImageSize) / 2;
            doc.addImage(
              base64String,
              'JPEG',
              coverImageX,
              60,
              coverImageSize,
              coverImageSize,
              undefined,
              'FAST'
            );
          }
          // Nullify to encourage GC
          base64String = null;
        } catch (err) {
          console.warn('Cover image failed:', err);
        }
      }

      // Metadata on cover
      doc.setFontSize(10);
      doc.setTextColor(100);
      const metaY = coverPage?.image?.blob ? 150 : 100;

      if (bookData.settings) {
        doc.text(`Reading Level: ${bookData.settings.level}`, pageWidth / 2, metaY, { align: 'center' });
        doc.text(`Tone: ${bookData.settings.tone > 0.7 ? 'Fun & Playful' : bookData.settings.tone < 0.3 ? 'Academic' : 'Balanced'}`, pageWidth / 2, metaY + 10, { align: 'center' });
        doc.text(`Style: ${bookData.settings.style > 0.7 ? 'Realistic' : bookData.settings.style < 0.3 ? 'Cartoonish' : 'Digital Art'}`, pageWidth / 2, metaY + 20, { align: 'center' });
      }

      doc.text(
        `Created with Living Textbook AI`,
        pageWidth / 2,
        pageHeight - 30,
        { align: 'center' }
      );
      doc.setFontSize(8);
      doc.text(
        `Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        pageWidth / 2,
        pageHeight - 22,
        { align: 'center' }
      );

      // Add page number to cover
      addFooter(doc, 1, (bookData.pages?.length || 1) + 1, pageWidth, pageHeight, margin);

      // === CONTENT PAGES ===
      const pages = bookData.pages || [];
      const totalPages = pages.length + 1; // +1 for cover

      for (let i = 0; i < pages.length; i++) {
        const page = pages[i];
        if (!page) continue;

        // Yield to main thread between pages to prevent freezing
        // Use requestAnimationFrame for better UI repaint, fallback to sleep
        if (i > 0) {
          await new Promise(resolve => {
            if (typeof requestAnimationFrame !== 'undefined') {
              requestAnimationFrame(() => resolve(null));
            } else {
              setTimeout(resolve, 10);
            }
          });
        }

        // Update progress
        setExportProgress(Math.round(((i + 1) / pages.length) * 100));

        // Add new page
        doc.addPage();
        const pdfPageNum = i + 2; // +1 for cover, +1 for 0-index

        // Page header with title
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30);
        doc.text(page.title || `Page ${i + 1}`, margin, margin + 10);

        // Page number indicator
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(128);
        doc.text(`Page ${i + 1} of ${pages.length}`, pageWidth - margin, margin + 10, { align: 'right' });

        // Add image if available - process asynchronously
        if (page.image?.blob) {
          try {
            // Yield to main thread before image processing
            await sleep(10);
            base64String = await blobToBase64(page.image.blob);
            if (base64String) {
              const imageHeight = contentWidth;
              const imageY = margin + 25;

              doc.addImage(
                base64String,
                'JPEG',
                margin,
                imageY,
                contentWidth,
                imageHeight,
                undefined,
                'FAST'
              );

              // Add content text below image
              doc.setFontSize(12);
              doc.setFont('helvetica', 'normal');
              doc.setTextColor(50);
              const textY = imageY + imageHeight + 15;
              const availableHeight = pageHeight - textY - margin - 20; // Reserve space for footer
              const { fontSize, splitText } = calculateFitText(doc, page.content || '', contentWidth, availableHeight, 12);
              doc.setFontSize(fontSize);
              doc.text(splitText, margin, textY);
            } else {
              // Fallback: text only
              const textY = margin + 25;
              const availableHeight = pageHeight - textY - margin - 20;
              const { fontSize, splitText } = calculateFitText(doc, page.content || '', contentWidth, availableHeight, 12);
              doc.setFontSize(fontSize);
              doc.text(splitText, margin, textY);
            }
            // Nullify to encourage GC
            base64String = null;
          } catch (err) {
            console.warn(`Page ${i + 1} image failed:`, err);
            // Fallback to text only
            const textY = margin + 25;
            const availableHeight = pageHeight - textY - margin - 20;
            const { fontSize, splitText } = calculateFitText(doc, page.content || '', contentWidth, availableHeight, 12);
            doc.setFontSize(fontSize);
            doc.text(splitText, margin, textY);
          }
        } else {
          // No image - text only
          const textY = margin + 25;
          const availableHeight = pageHeight - textY - margin - 20;
          const { fontSize, splitText } = calculateFitText(doc, page.content || '', contentWidth, availableHeight, 12);
          doc.setFontSize(fontSize);
          doc.text(splitText, margin, textY);
        }

        // Add footer
        addFooter(doc, pdfPageNum, totalPages, pageWidth, pageHeight, margin);
      }

      // Set PDF metadata
      doc.setProperties({
        title: bookData.subject,
        subject: `Educational Book - ${bookData.settings?.level || 'General'} Level`,
        author: 'Living Textbook AI',
        creator: 'Living Textbook',
        keywords: `education, ${bookData.subject}, AI-generated, ${bookData.settings?.level || 'general'}`,
      });

      // Yield before saving
      await sleep(0);

      // Save the PDF with formatted filename
      const safeSubject = bookData.subject.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
      const dateStr = new Date().toISOString().split('T')[0];
      const filename = `LivingTextbook_${safeSubject}_${dateStr}.pdf`;
      doc.save(filename);

      setExportProgress(100);
    } catch (error) {
      console.error('PDF export failed:', error);
      setExportError((error as Error).message || 'Failed to export PDF');
    } finally {
      // Ensure base64 string is nullified
      base64String = null;
      setExporting(false);
    }
  }, [bookData, addFooter]);

  /**
   * Cancel export (reset state)
   */
  const cancelExport = useCallback(() => {
    setExporting(false);
    setExportProgress(0);
    setExportError(null);
  }, []);

  /**
   * Reset export state
   */
  const resetExport = useCallback(() => {
    setExporting(false);
    setExportProgress(0);
    setExportError(null);
  }, []);

  return {
    // State
    exporting,
    exportProgress,
    exportError,

    // Actions
    exportPDF,
    cancelExport,
    resetExport,
  };
}

export default usePdfExport;
