import React, { useState, useCallback } from 'react';
import jsPDF from 'jspdf';
import './BookRenderer.css';

/**
 * Convert blob to base64 data URL
 * @param {Blob} blob - Image blob
 * @returns {Promise<string>} - Base64 data URL
 */
const blobToBase64 = (blob) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

/**
 * BookRenderer component with enhanced PDF export and page navigation
 */
const BookRenderer = ({ bookData, loading, currentPage, totalPages, onPageChange, hasOutline }) => {
  const [exporting, setExporting] = useState(false);
  const [isFlipping, setIsFlipping] = useState(false);

  /**
   * Enhanced PDF export with image embedding
   */
  const exportPDF = useCallback(async () => {
    if (!bookData) return;

    setExporting(true);

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;

      // Title
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text(bookData.subject, margin, margin + 10);

      // Add image if available
      if (bookData.image?.blob) {
        const imageData = await blobToBase64(bookData.image.blob);
        if (imageData) {
          // Maintain 1:1 aspect ratio (sd-turbo generates 512x512 images)
          const imageHeight = contentWidth;
          const imageY = margin + 20;

          // Add image centered on the page
          doc.addImage(
            imageData,
            'JPEG',
            margin,
            imageY,
            contentWidth,
            imageHeight,
            undefined,
            'FAST'
          );

          // Add content text below image
          doc.setFontSize(12);
          doc.setFont('helvetica', 'normal');
          const textY = imageY + imageHeight + 15;
          const splitText = doc.splitTextToSize(bookData.content, contentWidth);
          doc.text(splitText, margin, textY);
        } else {
          // Fallback: text only if image conversion failed
          doc.setFontSize(12);
          doc.setFont('helvetica', 'normal');
          const splitText = doc.splitTextToSize(bookData.content, contentWidth);
          doc.text(splitText, margin, margin + 30);
        }
      } else {
        // No image - text only
        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        const splitText = doc.splitTextToSize(bookData.content, contentWidth);
        doc.text(splitText, margin, margin + 30);
      }

      // Add metadata
      doc.setProperties({
        title: bookData.subject,
        subject: `Generated by Living Textbook - ${bookData.settings?.level || 'General'}`,
        creator: 'Living Textbook',
      });

      // Save the PDF
      const filename = `${bookData.subject.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '')}.pdf`;
      doc.save(filename);
    } catch (error) {
      console.error('PDF export failed:', error);
      alert('Failed to export PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  }, [bookData]);

  /**
   * Handle page change with animation
   */
  const handlePageChange = useCallback((newPage) => {
    if (newPage < 0 || newPage >= totalPages) return;
    setIsFlipping(true);
    setTimeout(() => {
      onPageChange(newPage);
      setIsFlipping(false);
    }, 300);
  }, [onPageChange, totalPages]);

  // Empty state
  if (!bookData && !loading && !hasOutline) {
    return (
      <div className="book-empty">
        <h2>Your book will appear here</h2>
        <p>Enter a subject and click "Generate" to start your learning journey.</p>
      </div>
    );
  }

  // Loading state (generating outline)
  if (loading && !bookData) {
    return (
      <div className="book-loading">
        <div className="spinner"></div>
        <p>Creating book outline...</p>
      </div>
    );
  }

  // Page loading state
  if (loading && bookData) {
    return (
      <div className="book-loading">
        <div className="spinner"></div>
        <p>Generating page {currentPage + 1} of {totalPages}...</p>
      </div>
    );
  }

  return (
    <div className="book-container">
      <div className={`book-page ${isFlipping ? 'flipping' : ''}`}>
        <div className="page-header">
          <span className="page-indicator">Page {currentPage + 1} of {totalPages}</span>
          {bookData.title && <span className="page-title">{bookData.title}</span>}
        </div>
        
        <div className="page-image">
          {bookData.image?.imageUrl ? (
            <img src={bookData.image.imageUrl} alt={bookData.subject} />
          ) : (
            <div className="image-placeholder">Visualizing...</div>
          )}
        </div>
        <div className="page-content">
          <h1>{bookData.subject}</h1>
          <p>{bookData.content}</p>
        </div>
      </div>

      <div className="book-controls">
        <button
          onClick={() => handlePageChange(currentPage - 1)}
          disabled={currentPage === 0}
          className="nav-btn prev-btn"
        >
          ← Previous
        </button>
        
        <button
          onClick={exportPDF}
          className="export-btn"
          disabled={exporting || !bookData}
        >
          {exporting ? 'Exporting...' : 'Download PDF'}
        </button>
        
        <button
          onClick={() => handlePageChange(currentPage + 1)}
          disabled={currentPage === totalPages - 1}
          className="nav-btn next-btn"
        >
          Next →
        </button>
      </div>

      <div className="page-dots">
        {Array.from({ length: totalPages }).map((_, idx) => (
          <span
            key={idx}
            className={`dot ${idx === currentPage ? 'active' : ''}`}
            onClick={() => handlePageChange(idx)}
          />
        ))}
      </div>
    </div>
  );
};

export default BookRenderer;
