import React, { useState, useCallback } from 'react';
import jsPDF from 'jspdf';
import './BookRenderer.css';

/**
 * Convert image URL to base64 data URL
 * @param {string} url - Image URL (object URL or data URL)
 * @returns {Promise<string>} - Base64 data URL
 */
const imageUrlToBase64 = async (url) => {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error('Failed to convert image to base64:', error);
    return null;
  }
};

/**
 * BookRenderer component with enhanced PDF export
 */
const BookRenderer = ({ bookData, loading }) => {
  const [exporting, setExporting] = useState(false);

  /**
   * Enhanced PDF export with image embedding
   */
  const exportPDF = useCallback(async () => {
    if (!bookData) return;

    setExporting(true);

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;

      // Title
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text(bookData.subject, margin, margin + 10);

      // Add image if available
      if (bookData.image) {
        const imageData = await imageUrlToBase64(bookData.image);
        if (imageData) {
          const imageHeight = 100; // Fixed height for the image
          const imageY = margin + 20;
          
          // Add image centered on the page
          doc.addImage(
            imageData,
            'JPEG',
            margin,
            imageY,
            contentWidth,
            imageHeight,
            undefined,
            'FAST'
          );

          // Add content text below image
          doc.setFontSize(12);
          doc.setFont('helvetica', 'normal');
          const textY = imageY + imageHeight + 15;
          const splitText = doc.splitTextToSize(bookData.content, contentWidth);
          doc.text(splitText, margin, textY);
        } else {
          // Fallback: text only if image conversion failed
          doc.setFontSize(12);
          doc.setFont('helvetica', 'normal');
          const splitText = doc.splitTextToSize(bookData.content, contentWidth);
          doc.text(splitText, margin, margin + 30);
        }
      } else {
        // No image - text only
        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        const splitText = doc.splitTextToSize(bookData.content, contentWidth);
        doc.text(splitText, margin, margin + 30);
      }

      // Add metadata
      doc.setProperties({
        title: bookData.subject,
        subject: `Generated by Living Textbook - ${bookData.settings?.level || 'General'}`,
        creator: 'Living Textbook',
      });

      // Save the PDF
      const filename = `${bookData.subject.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '')}.pdf`;
      doc.save(filename);
    } catch (error) {
      console.error('PDF export failed:', error);
      alert('Failed to export PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  }, [bookData]);

  // Empty state
  if (!bookData && !loading) {
    return (
      <div className="book-empty">
        <h2>Your book will appear here</h2>
        <p>Enter a subject and click "Generate" to start your learning journey.</p>
      </div>
    );
  }

  // Loading state
  if (loading) {
    return (
      <div className="book-loading">
        <div className="spinner"></div>
        <p>Consulting the AI library...</p>
      </div>
    );
  }

  return (
    <div className="book-container">
      <div className="book-page">
        <div className="page-image">
          {bookData.image ? (
            <img src={bookData.image} alt={bookData.subject} />
          ) : (
            <div className="image-placeholder">Visualizing...</div>
          )}
        </div>
        <div className="page-content">
          <h1>{bookData.subject}</h1>
          <p>{bookData.content}</p>
        </div>
      </div>

      <div className="book-controls">
        <button 
          onClick={exportPDF} 
          className="export-btn"
          disabled={exporting}
        >
          {exporting ? 'Exporting...' : 'Download PDF'}
        </button>
      </div>
    </div>
  );
};

export default BookRenderer;
