import React, { useState, useCallback, useEffect } from 'react';
import jsPDF from 'jspdf';
import './BookRenderer.css';

/**
 * Convert blob to base64 data URL
 * @param {Blob} blob - Image blob
 * @returns {Promise<string>} - Base64 data URL
 */
const blobToBase64 = (blob) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

/**
 * BookRenderer component with enhanced PDF export and page navigation
 */
const BookRenderer = ({ bookData, loading, currentPage, totalPages, onPageChange, hasOutline, generateImage }) => {
  const [exporting, setExporting] = useState(false);
  const [isFlipping, setIsFlipping] = useState(false);
  const [regeneratingImage, setRegeneratingImage] = useState(false);

  /**
   * Enhanced PDF export with cover page, all pages, and professional formatting
   */
  const exportPDF = useCallback(async () => {
    if (!bookData || !bookData.subject) return;

    setExporting(true);

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;

      // Helper function to add footer with page number
      const addFooter = (pageNum, totalPages) => {
        doc.setFontSize(8);
        doc.setTextColor(128);
        doc.text(
          `Page ${pageNum} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
        doc.text(
          'Generated by Living Textbook',
          margin,
          pageHeight - 10
        );
        doc.text(
          new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }),
          pageWidth - margin,
          pageHeight - 10,
          { align: 'right' }
        );
      };

      // === COVER PAGE ===
      // Add gradient background effect with rectangles
      doc.setFillColor(102, 126, 234);
      doc.rect(0, 0, pageWidth, 60, 'F');
      
      // Title
      doc.setFontSize(28);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255);
      doc.text(bookData.subject, pageWidth / 2, 35, { align: 'center' });

      // Subtitle
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(255);
      doc.text(
        `A ${bookData.settings?.level || 'General'} Level Educational Book`,
        pageWidth / 2,
        45,
        { align: 'center' }
      );

      // Cover image if available
      if (bookData.image?.blob) {
        try {
          const imageData = await blobToBase64(bookData.image.blob);
          if (imageData) {
            const coverImageSize = 80;
            const coverImageX = (pageWidth - coverImageSize) / 2;
            doc.addImage(
              imageData,
              'JPEG',
              coverImageX,
              60,
              coverImageSize,
              coverImageSize,
              undefined,
              'FAST'
            );
          }
        } catch (err) {
          console.warn('Cover image failed:', err);
        }
      }

      // Metadata on cover
      doc.setFontSize(10);
      doc.setTextColor(100);
      const metaY = bookData.image?.blob ? 150 : 100;
      
      if (bookData.settings) {
        doc.text(`Reading Level: ${bookData.settings.level}`, pageWidth / 2, metaY, { align: 'center' });
        doc.text(`Tone: ${bookData.settings.tone > 0.7 ? 'Fun & Playful' : bookData.settings.tone < 0.3 ? 'Academic' : 'Balanced'}`, pageWidth / 2, metaY + 10, { align: 'center' });
        doc.text(`Style: ${bookData.settings.style > 0.7 ? 'Realistic' : bookData.settings.style < 0.3 ? 'Cartoonish' : 'Digital Art'}`, pageWidth / 2, metaY + 20, { align: 'center' });
      }
      
      doc.text(
        `Created with Living Textbook AI`,
        pageWidth / 2,
        pageHeight - 30,
        { align: 'center' }
      );
      doc.setFontSize(8);
      doc.text(
        `Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        pageWidth / 2,
        pageHeight - 22,
        { align: 'center' }
      );

      // Add page number to cover
      addFooter(1, (bookData.pages?.length || 1) + 1);

      // === CONTENT PAGES ===
      const pages = bookData.pages || [];
      
      for (let i = 0; i < pages.length; i++) {
        const page = pages[i];
        if (!page) continue;

        // Add new page
        doc.addPage();
        const pdfPageNum = i + 2; // +1 for cover, +1 for 0-index

        // Page header with title
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30);
        doc.text(page.title || `Page ${i + 1}`, margin, margin + 10);

        // Page number indicator
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(128);
        doc.text(`Page ${i + 1} of ${pages.length}`, pageWidth - margin, margin + 10, { align: 'right' });

        // Add image if available
        if (page.image?.blob) {
          try {
            const imageData = await blobToBase64(page.image.blob);
            if (imageData) {
              const imageHeight = contentWidth;
              const imageY = margin + 25;

              doc.addImage(
                imageData,
                'JPEG',
                margin,
                imageY,
                contentWidth,
                imageHeight,
                undefined,
                'FAST'
              );

              // Add content text below image
              doc.setFontSize(12);
              doc.setFont('helvetica', 'normal');
              doc.setTextColor(50);
              const textY = imageY + imageHeight + 15;
              const splitText = doc.splitTextToSize(page.content || '', contentWidth);
              doc.text(splitText, margin, textY);
            } else {
              // Fallback: text only
              doc.setFontSize(12);
              doc.setFont('helvetica', 'normal');
              doc.setTextColor(50);
              const splitText = doc.splitTextToSize(page.content || '', contentWidth);
              doc.text(splitText, margin, margin + 25);
            }
          } catch (err) {
            console.warn(`Page ${i + 1} image failed:`, err);
            // Fallback to text only
            doc.setFontSize(12);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(50);
            const splitText = doc.splitTextToSize(page.content || '', contentWidth);
            doc.text(splitText, margin, margin + 25);
          }
        } else {
          // No image - text only
          doc.setFontSize(12);
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(50);
          const splitText = doc.splitTextToSize(page.content || '', contentWidth);
          doc.text(splitText, margin, margin + 25);
        }

        // Add footer
        addFooter(pdfPageNum, pages.length + 1);
      }

      // Set PDF metadata
      doc.setProperties({
        title: bookData.subject,
        subject: `Educational Book - ${bookData.settings?.level || 'General'} Level`,
        author: 'Living Textbook AI',
        creator: 'Living Textbook',
        keywords: `education, ${bookData.subject}, AI-generated, ${bookData.settings?.level || 'general'}`,
        creationDate: new Date(),
      });

      // Save the PDF with formatted filename
      const safeSubject = bookData.subject.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
      const dateStr = new Date().toISOString().split('T')[0];
      const filename = `LivingTextbook_${safeSubject}_${dateStr}.pdf`;
      doc.save(filename);
    } catch (error) {
      console.error('PDF export failed:', error);
      alert('Failed to export PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  }, [bookData]);

  /**
   * Handle page change with animation
   */
  const handlePageChange = useCallback((newPage) => {
    if (newPage < 0 || newPage >= totalPages) return;
    setIsFlipping(true);
    setTimeout(() => {
      onPageChange(newPage);
      setIsFlipping(false);
    }, 300);
  }, [onPageChange, totalPages]);

  /**
   * Regenerate image for current page
   */
  const handleRegenerateImage = useCallback(async () => {
    if (!bookData || !generateImage) return;

    setRegeneratingImage(true);

    try {
      // Use the current image prompt or generate a new one based on subject
      const imagePrompt = bookData.imagePrompt || `A depiction of ${bookData.subject}, educational, bright colors, high quality.`;
      
      const result = await generateImage(imagePrompt, { skipCache: true });
      
      if (result && result.imageUrl) {
        // Update book data with new image - this will be handled by parent component
        // For now, we'll just trigger a re-render by updating local state
        window.dispatchEvent(new CustomEvent('book-image-updated', {
          detail: { currentPage, newImage: result }
        }));
      }
    } catch (err) {
      console.error('Failed to regenerate image:', err);
      alert('Failed to regenerate image. Please try again.');
    } finally {
      setRegeneratingImage(false);
    }
  }, [bookData, generateImage, currentPage]);

  /**
   * Keyboard navigation for pages
   */
  useEffect(() => {
    const handleKeyDown = (e) => {
      // Only handle arrow keys when not in an input field
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') {
        return;
      }

      switch (e.key) {
        case 'ArrowLeft':
          e.preventDefault();
          if (currentPage > 0) {
            handlePageChange(currentPage - 1);
          }
          break;
        case 'ArrowRight':
          e.preventDefault();
          if (currentPage < totalPages - 1) {
            handlePageChange(currentPage + 1);
          }
          break;
        case 'Home':
          e.preventDefault();
          if (currentPage !== 0) {
            handlePageChange(0);
          }
          break;
        case 'End':
          e.preventDefault();
          if (currentPage !== totalPages - 1) {
            handlePageChange(totalPages - 1);
          }
          break;
        default:
          break;
      }
    };

    // Only attach listener when we have a book to navigate
    if (bookData && totalPages > 0) {
      window.addEventListener('keydown', handleKeyDown);
      return () => {
        window.removeEventListener('keydown', handleKeyDown);
      };
    }
  }, [currentPage, totalPages, bookData, handlePageChange]);

  // Empty state
  if (!bookData && !loading && !hasOutline) {
    return (
      <div className="book-empty">
        <h2>Your book will appear here</h2>
        <p>Enter a subject and click "Generate" to start your learning journey.</p>
      </div>
    );
  }

  // Loading state (generating outline)
  if (loading && !bookData) {
    return (
      <div className="book-loading">
        <div className="spinner"></div>
        <p>Creating book outline...</p>
      </div>
    );
  }

  // Page loading state
  if (loading && bookData) {
    return (
      <div className="book-loading">
        <div className="spinner"></div>
        <p>Generating page {currentPage + 1} of {totalPages}...</p>
      </div>
    );
  }

  return (
    <div 
      className="book-container"
      role="region"
      aria-label="Book reader"
      tabIndex={0}
    >
      <div 
        className={`book-page ${isFlipping ? 'flipping' : ''}`}
        role="article"
        aria-label={`Page ${currentPage + 1} of ${totalPages}`}
      >
        <div className="page-header">
          <span className="page-indicator" aria-live="polite">Page {currentPage + 1} of {totalPages}</span>
          {bookData.title && <span className="page-title">{bookData.title}</span>}
        </div>

        <div className="page-image">
          {bookData.image?.imageUrl ? (
            <>
              <img src={bookData.image.imageUrl} alt={bookData.image.alt || `Illustration for ${bookData.subject}`} />
              <button
                className="regenerate-image-btn"
                onClick={handleRegenerateImage}
                disabled={regeneratingImage}
                aria-label="Regenerate image for this page"
                title="Generate a new image for this page"
              >
                {regeneratingImage ? '🎨 Generating...' : '🔄 New Image'}
              </button>
            </>
          ) : (
            <div className="image-placeholder" role="status">Visualizing...</div>
          )}
        </div>
        <div className="page-content">
          <h1>{bookData.subject}</h1>
          <p>{bookData.content}</p>
        </div>
      </div>

      <div className="book-controls" role="navigation" aria-label="Page navigation">
        <button
          onClick={() => handlePageChange(currentPage - 1)}
          disabled={currentPage === 0}
          className="nav-btn prev-btn"
          aria-label="Go to previous page"
        >
          ← Previous
        </button>

        <button
          onClick={exportPDF}
          className="export-btn"
          disabled={exporting || !bookData}
          aria-label="Download complete book as PDF"
          title="Export all pages as a PDF book"
        >
          {exporting ? '📄 Exporting Book...' : '📕 Download Book PDF'}
        </button>

        <button
          onClick={() => handlePageChange(currentPage + 1)}
          disabled={currentPage === totalPages - 1}
          className="nav-btn next-btn"
          aria-label="Go to next page"
        >
          Next →
        </button>
      </div>

      <div className="page-dots" role="tablist" aria-label="Page selection">
        {Array.from({ length: totalPages }).map((_, idx) => (
          <span
            key={idx}
            className={`dot ${idx === currentPage ? 'active' : ''}`}
            onClick={() => handlePageChange(idx)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                handlePageChange(idx);
              }
            }}
            role="tab"
            aria-selected={idx === currentPage}
            aria-label={`Go to page ${idx + 1}`}
            tabIndex={idx === currentPage ? 0 : -1}
          />
        ))}
      </div>
    </div>
  );
};

export default BookRenderer;
